export const MODERATION_MAX_LINKS_REVIEW = 3;
export const MODERATION_MAX_LINKS_REJECT = 6;
export const MODERATION_REPEAT_REVIEW_THRESHOLD = 8;
export const MODERATION_REPEAT_REJECT_THRESHOLD = 14;
export const MODERATION_MIN_TEXT_LENGTH = 2;

