import React, { useEffect, useMemo, useRef, useState } from "react";
import { AdminApiError, adminFetch } from "../../lib/admin-api-client";
import GlassConfirmDialog from "../common/GlassConfirmDialog";
import { useAdminSession } from "./useAdminSession";

type Status = "draft" | "published" | "hidden" | "archived";
type Device = Record<string, unknown> & { id:string; slug:string; brandName:string; name:string; publicationStatus:Status; slugLocked:boolean; releaseYear?:string | null; productImageUrl?:string | null; updatedAt?:string | null };
type Form = Record<string, string> & { id:string; slug:string; brandKey:string; brandName:string; name:string; shortDescription:string; longDescription:string; imageAlt:string; category:string; routeLabel:string; routeDescription:string; releaseYear:string; productImageUrl:string; productUrl:string; officialProductUrl:string; buyUrl:string; positioning:string; availability:string; typeLabel:string; statusLabel:string; officialImageUrl:string; keyLimitations:string; bestFor:string; notIdealFor:string; keySpecs:string; fullSpecs:string; media:string };
const emptyForm:Form={id:"",slug:"",brandKey:"",brandName:"",name:"",shortDescription:"",longDescription:"",imageAlt:"",category:"smart_glasses",routeLabel:"",routeDescription:"",releaseYear:"",productImageUrl:"",productUrl:"",officialProductUrl:"",buyUrl:"",positioning:"",availability:"",typeLabel:"",statusLabel:"",officialImageUrl:"",keyLimitations:"",bestFor:"",notIdealFor:"",keySpecs:"",fullSpecs:"",media:""};
const filters:["all"|Status,string][]=[["all","全部"],["published","已发布"],["draft","草稿"],["hidden","已隐藏"],["archived","已归档"]];
const safeMessage=(error:unknown)=>error instanceof AdminApiError?error.message:"操作失败，请稍后重试。";
type AdminDevicesDashboardDeps = { useSession: typeof useAdminSession; fetchAdmin: typeof adminFetch };
const toList=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==="string").join("\n"):"";
const toJson=(value:unknown)=>value&&typeof value==="object"?JSON.stringify(value,null,2):"";
function toForm(device?:Device):Form { if(!device)return {...emptyForm}; const field=(name:string)=>typeof device[name]==="string"?device[name] as string:""; return {...emptyForm,id:device.id,slug:device.slug,brandKey:field("brandKey"),brandName:device.brandName,name:device.name,shortDescription:field("shortDescription"),longDescription:field("longDescription"),imageAlt:field("imageAlt"),category:field("category")||"smart_glasses",routeLabel:field("routeLabel"),routeDescription:field("routeDescription"),releaseYear:field("releaseYear"),productImageUrl:field("productImageUrl"),productUrl:field("productUrl"),officialProductUrl:field("officialProductUrl"),buyUrl:field("buyUrl"),positioning:field("positioning"),availability:field("availability"),typeLabel:field("typeLabel"),statusLabel:field("statusLabel"),officialImageUrl:field("officialImageUrl"),keyLimitations:toList(device.keyLimitations),bestFor:toList(device.bestFor),notIdealFor:toList(device.notIdealFor),keySpecs:toJson(device.keySpecs),fullSpecs:toJson(device.fullSpecs),media:toJson(device.media)}; }
function lines(value:string){return value.split("\n").map((item)=>item.trim()).filter(Boolean);}
function payload(form:Form){const parse=(value:string,label:string)=>{if(!value.trim())return undefined;try{return JSON.parse(value);}catch{throw new Error(`${label} 必须是有效 JSON。`);}}; const data:Record<string,unknown>={brandKey:form.brandKey.trim(),brandName:form.brandName.trim(),name:form.name.trim(),shortDescription:form.shortDescription.trim(),longDescription:form.longDescription.trim(),imageAlt:form.imageAlt.trim(),category:form.category.trim(),routeLabel:form.routeLabel.trim(),routeDescription:form.routeDescription.trim()}; for(const key of ["slug","releaseYear","productImageUrl","productUrl","officialProductUrl","buyUrl","positioning","availability","typeLabel","statusLabel","officialImageUrl"] as const)if(form[key].trim())data[key]=form[key].trim(); for(const key of ["bestFor","notIdealFor","keyLimitations"] as const)if(form[key].trim())data[key]=lines(form[key]); for(const key of ["media","keySpecs","fullSpecs"] as const){const value=parse(form[key],key);if(value!==undefined)data[key]=value;}return data;}
export function createAdminDevicesDashboard(deps: AdminDevicesDashboardDeps){ return function AdminDevicesDashboard(){
 const admin=deps.useSession(); const inFlightMutations=useRef(new Set<string>()); const [activeMutationKeys,setActiveMutationKeys]=useState<Set<string>>(new Set()); const [devices,setDevices]=useState<Device[]>([]),[filter,setFilter]=useState<"all"|Status>("all"),[form,setForm]=useState<Form>({...emptyForm}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[publishTarget,setPublishTarget]=useState<Device|null>(null),[deleteTarget,setDeleteTarget]=useState<Device|null>(null),[restoreTarget,setRestoreTarget]=useState<Status>("draft"); const selectedMutationKey=form.id?`device:${form.id}`:"create"; const saving=activeMutationKeys.has(selectedMutationKey);
 const load=async()=>{if(!admin.session)return;setLoading(true);setError("");try{const result=await deps.fetchAdmin<{devices?:Device[]}>("/api/admin/devices",{session:admin.session});setDevices(result.devices??[]);}catch(e){setError(safeMessage(e));}finally{setLoading(false);}}; useEffect(()=>{void load();},[admin.session]);
 const visible=useMemo(()=>filter==="all"?devices:devices.filter((item)=>item.publicationStatus===filter),[devices,filter]); const counts=useMemo(()=>Object.fromEntries(filters.map(([value])=>[value,value==="all"?devices.length:devices.filter((item)=>item.publicationStatus===value).length])),[devices]);
 const select=(device:Device)=>{setForm(toForm(device));setError("");}; const patch=(key:keyof Form,value:string)=>setForm((current)=>({...current,[key]:value}));
 const mutate=async(method:"POST"|"PATCH"|"DELETE", body:Record<string,unknown>)=>{if(!admin.session)return;const key=typeof body.id==="string"?`device:${body.id}`:"create";if(inFlightMutations.current.has(key))return false;inFlightMutations.current.add(key);setActiveMutationKeys((current)=>new Set(current).add(key));setError("");try{const result=await deps.fetchAdmin<{device?:Device}>("/api/admin/devices",{session:admin.session,method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(result.device)setDevices((current)=>current.some((d)=>d.id===result.device!.id)?current.map((d)=>d.id===result.device!.id?result.device!:d):[result.device!,...current]);await load();return true;}catch(e){setError(safeMessage(e));return false;}finally{inFlightMutations.current.delete(key);setActiveMutationKeys((current)=>{const next=new Set(current);next.delete(key);return next;});}};
 const save=async()=>{try{const data=payload(form);if(form.id)await mutate("PATCH",{id:form.id,...data});else{const ok=await mutate("POST",data);if(ok)setForm({...emptyForm});}}catch(e){setError(e instanceof Error?e.message:"表单无效。");}};
 const lifecycle=(status:Status)=>{if(!form.id)return;void mutate("PATCH",{id:form.id,publicationStatus:status});};
 return <section className="admin-news-dashboard" aria-label="设备管理">
  <div className="admin-news-toolbar"><div><h2>设备库管理</h2><p>所有操作通过受保护的设备管理 API 完成。新设备始终先保存为草稿。</p></div><button type="button" className="community-button" onClick={()=>{setForm({...emptyForm});setError("");}}>创建设备</button></div>
  <div className="admin-news-toolbar__filters" aria-label="发布状态筛选">{filters.map(([value,label])=><button key={value} type="button" className={filter===value?"community-button":"community-button--secondary"} onClick={()=>setFilter(value)}>{label} ({counts[value]??0})</button>)}</div>
  {error?<div className="comment-inline-error" role="alert">{error} <button type="button" className="community-link" onClick={()=>void load()}>重试</button></div>:null}
  <div className="admin-news-dashboard__grid"><div className="admin-news-dashboard__list"><div className="admin-news-dashboard__list-head"><div><strong>设备列表</strong><p>草稿、已发布、隐藏和归档记录均可管理。</p></div></div>{loading?<p className="community-meta">正在加载设备...</p>:visible.length===0?<div className="community-empty"><strong>暂无设备</strong><p>调整筛选条件或创建第一个草稿。</p></div>:visible.map((device)=><button key={device.id} type="button" className={`admin-news-card${form.id===device.id?" is-active":""}`} onClick={()=>select(device)}><div className="admin-news-card__meta"><span className="community-tag">{device.publicationStatus}</span><span className="community-meta">{device.slug}</span></div><strong>{device.name}</strong><p>{device.brandName}{device.releaseYear?` · ${device.releaseYear}`:""}</p></button>)}</div>
   <form className="admin-news-form" onSubmit={(event)=>{event.preventDefault();void save();}}><div className="admin-news-form__head"><div><strong>{form.id?"编辑设备":"新建设备"}</strong><p>{form.id?"内容更改保存后才会成为当前记录。":"创建后保持草稿，发布由独立操作确认。"}</p></div></div>
   <section className="admin-news-form__section"><div className="admin-news-form__grid">{([['brandKey','品牌代码'],['brandName','品牌名称'],['name','设备名称'],['slug','链接 slug'],['releaseYear','发布年份'],['category','分类'],['typeLabel','类型标签'],['statusLabel','状态标签'],['availability','可用性'],['imageAlt','图片替代文字'],['productImageUrl','产品图片 URL'],['officialImageUrl','官网图片 URL'],['productUrl','产品链接'],['officialProductUrl','官网链接'],['buyUrl','购买链接']] as [keyof Form,string][]).map(([key,label])=><label key={key} className="community-form-field"><span>{label}</span><input value={form[key]} disabled={key==='slug'&&Boolean((devices.find((d)=>d.id===form.id))?.slugLocked)} onChange={(e)=>patch(key,e.target.value)} />{key==='slug'&&form.id&&devices.find((d)=>d.id===form.id)?.slugLocked?<small className="community-meta">首次发布后链接已永久锁定。</small>:null}</label>)}</div></section>
   <section className="admin-news-form__section">{([['shortDescription','简短描述'],['longDescription','详细描述'],['positioning','定位'],['routeLabel','路由标签'],['routeDescription','路由说明'],['bestFor','适合对象，每行一项'],['notIdealFor','不适合对象，每行一项'],['keyLimitations','限制，每行一项'],['media','媒体 JSON'],['keySpecs','关键规格 JSON'],['fullSpecs','完整规格 JSON']] as [keyof Form,string][]).map(([key,label])=><label key={key} className="community-form-field"><span>{label}</span><textarea rows={key==='longDescription'||key==='fullSpecs'?6:3} value={form[key]} onChange={(e)=>patch(key,e.target.value)} /></label>)}</section>
   <div className="admin-news-form__actions"><button type="submit" className="community-button" disabled={saving}>{saving?"保存中...":form.id?"保存修改":"创建草稿"}</button>{form.id?<><button type="button" className="community-button--secondary" disabled={saving} onClick={()=>{const selected=devices.find((d)=>d.id===form.id);if(selected)setPublishTarget(selected);}}>发布</button><button type="button" className="community-button--secondary" disabled={saving} onClick={()=>lifecycle("hidden")}>隐藏</button><button type="button" className="community-button--secondary" disabled={saving} onClick={()=>lifecycle("archived")}>归档</button>{devices.find((d)=>d.id===form.id)?.publicationStatus==="archived"?<><label className="community-form-field"><span>恢复为</span><select value={restoreTarget} onChange={(e)=>setRestoreTarget(e.target.value as Status)}><option value="draft">草稿</option><option value="hidden">隐藏</option><option value="published">已发布</option></select></label><button type="button" className="community-button--secondary" disabled={saving} onClick={()=>lifecycle(restoreTarget)}>恢复</button><button type="button" className="community-button--secondary admin-action-danger" disabled={saving} onClick={()=>setDeleteTarget(devices.find((d)=>d.id===form.id)??null)}>永久删除</button></>:null}</>:null}</div></form></div>
  <GlassConfirmDialog open={Boolean(publishTarget)} title="发布设备" description="发布后 slug 将永久锁定。继续吗？" detail={publishTarget?.name} confirmLabel="确认发布" cancelLabel="取消" loading={saving} error={error} onCancel={()=>setPublishTarget(null)} onConfirm={()=>{if(!publishTarget)return;void mutate("PATCH",{id:publishTarget.id,publicationStatus:"published"}).then((ok)=>{if(ok)setPublishTarget(null);});}} />
  <GlassConfirmDialog open={Boolean(deleteTarget)} title="永久删除设备" description="这会永久删除设备记录，且无法撤销。" detail={deleteTarget?.name} confirmLabel="确认永久删除" cancelLabel="取消" danger loading={saving} error={error} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>{if(!deleteTarget)return;void mutate("DELETE",{id:deleteTarget.id,confirmPermanentDelete:true}).then((ok)=>{if(ok){setDeleteTarget(null);setForm({...emptyForm});}});}} />
 </section>;
}; }

export default createAdminDevicesDashboard({ useSession: useAdminSession, fetchAdmin: adminFetch });
