import type { ResolvedLocale } from "../locale.ts";
import { formatPostTime } from "../../format-time.ts";

export const communityMessages = {
  "zh-CN": {
    tabFeed: "动态", feed: "帖子动态", feedDescription: "OpenGlass Hub 论坛公开帖子动态，支持推荐、最新与热门排序。",
    share: "分享", copied: "已复制", like: "点赞", unlike: "取消点赞", bookmark: "收藏", unbookmark: "取消收藏",
    composerTypes: { question: "求助", experience: "文字", review: "体验/评测", dev: "开发", news: "资讯", feedback: "反馈" }, composerTypeHints: { question: "兼容性、选购和使用问题。", experience: "适合一般讨论、观察记录和补充说明。", review: "适合完整总结、对比和长期观察。", dev: "围绕 SDK、权限、输入和系统能力讨论。", news: "适合手动整理的动态、公告和观察。", feedback: "对产品、社区和 Gaze Launcher 的建议。" },
    imageMetadata: "无法读取图片元信息：{name}", videoMetadata: "无法读取视频元信息：{name}", actionRateLimited: "操作过于频繁，请稍后再试。", postRejected: "这篇帖子可能违反社区规则，暂时无法发布。", invalidPostBody: "正文至少需要 1 个字符，且不能超过 50000 个字符。", invalidCredentials: "邮箱或密码错误。", emailUnconfirmed: "请先完成邮箱验证后再登录。", alreadyRegistered: "该邮箱已经注册，请直接登录。", videoUploadFailed: "视频上传失败。", videoInitFailed: "视频上传初始化失败", missingPublicAuthConfig: "缺少 PUBLIC_SUPABASE_URL 或 PUBLIC_SUPABASE_ANON_KEY。", maxMedia: "单帖最多上传 {count} 个媒体文件。", mediaTypes: "只支持 jpg / png / webp / gif 图片，以及 mp4 / webm / mov 视频。", imageMaxSize: "单张图片不能超过 50MB。", videoMaxSize: "单个视频不能超过 150MB。", oneVideo: "每个帖子最多上传 1 个视频。", totalMediaSize: "单帖媒体总大小不能超过 150MB。", metadataFailed: "读取媒体元信息失败。", createPostFailed: "发帖失败", unknownError: "未知错误", imageUploadFailed: "图片上传失败", mediaWriteFailed: "媒体写入失败", videoReview: "视频已提交审核。", publishedRedirecting: "发布成功，正在跳转到帖子页面。", postReview: "帖子已提交审核。", published: "发布成功。", checkingAuth: "正在检查登录状态...", loginPost: "登录后继续发帖", publishPost: "发布帖子", deviceDraft: "已根据 {name} 设备页带入一个中性讨论草稿，可继续修改。", postType: "帖子类型", loadingCircles: "正在加载圈子...", noAvailableCircles: "暂无可选圈子", chooseCircle: "选择要发布到的圈子", circleList: "圈子列表", title: "标题", body: "正文", mediaFiles: "媒体文件", dropMedia: "拖拽图片或视频到这里，或点击选择文件", cover: "封面", image: "图片", currentCover: "当前封面", setCover: "设为封面", submitPost: "提交帖子",
    writeComment: "写下你的想法...", commentPublished: "评论发布成功。", loginComment: "请先登录后再评论", requestFailed: "请求失败", commentReview: "评论已提交审核。", submitFailed: "提交失败", commentRejected: "这条评论可能违反社区规则，暂时无法发布。", commentRateLimited: "评论过于频繁，请稍后再试。", commentUnconfigured: "评论功能未配置", signInComment: "登录后即可发表评论", goLogin: "前往登录", publishComment: "发表评论", cancelReply: "取消回复", submitting: "提交中...", publishReply: "发布回复", submitComment: "发布评论",
    checkingPermission: "检查管理权限...", manageCircle: "管理圈子", confirm: "确认", cancel: "取消", processing: "处理中...", confirmationInput: "输入确认内容",
    report: "举报", reportInvalid: "举报信息无效，请检查后重试。", reportGone: "该内容已不可见，无需重复举报。", reportRateLimited: "提交过于频繁，请稍后再试。", loginReport: "请先登录后再举报。", reportReasonShort: "补充说明至少需要 5 个字。", reportFailed: "举报失败。", reportHandled: "该内容已在处理或已不可见，无需重复举报。", reportDuplicate: "你最近已经举报过这条内容，管理员会统一处理。", reportSuccess: "已成功提交举报，管理员会尽快处理。", reportContent: "举报内容", reportIntro: "选择举报原因并补充说明，提交后管理员会查看。", reportDetails: "补充说明", reportDetailsPlaceholder: "可选，补充更多细节帮助管理员判断", reportDetailsHint: "可不填写；如填写，至少 5 个字。", reportLoginHint: "当前需要登录后才能提交举报。登录后会返回当前页面。", submitReport: "提交举报",
    reportReasons: { spam: "垃圾广告", harassment: "骚扰或攻击", hate: "仇恨内容", sexual: "性相关违规", violence: "暴力或威胁", illegal: "违法内容", off_platform_contact: "站外引流", misinformation: "虚假或误导信息", privacy: "隐私泄露", other: "其他" },
    unsupportedVideo: "浏览器不支持该视频。", expand: "放大查看", openExternalVideo: "打开外部视频", externalVideoHint: "在新窗口查看外部视频内容。",
    mediaThumbnails: "帖子媒体缩略图", link: "链接", closeMedia: "关闭媒体查看", close: "关闭", previousImage: "上一张", nextImage: "下一张",
    unknownUser: "未知用户", manageLoginRequired: "登录后才能管理圈子。", circleMissing: "圈子不存在。", manageProfileMissing: "当前账号缺少 profile，暂时无法管理圈子。", manageForbidden: "没有权限管理该圈子。", contentManageForbidden: "没有权限管理这条内容。", circleStatusMigration: "数据库还没有完成圈子状态 migration，请先执行最新 SQL。", circleDeleteRls: "圈子删除权限未就绪，请检查 circles RLS / policy。", circleDeleteFailed: "圈子删除失败，请稍后重试。", manageQueryFailed: "圈子管理信息查询失败，请稍后重试。", manageLoadFailed: "加载圈子管理数据失败", circleUpdated: "圈子信息已更新。", circleUpdateFailed: "更新圈子失败", postStatusFailed: "更新帖子状态失败", postHidden: "帖子已隐藏。", postRestored: "帖子已恢复公开。", postDeleted: "帖子已删除。", circleDeleted: "圈子已删除。", circleRestored: "圈子已恢复。", circleStatusFailed: "更新圈子状态失败", circleDeletedRedirect: "圈子已删除，正在返回圈子列表。", commentRemoved: "评论已删除。", commentRestored: "评论已恢复。", commentStatusFailed: "更新评论状态失败", loadingManage: "正在加载圈子管理数据...", manageOwnedHint: "登录后才能管理自己创建的圈子。", backCircleDetail: "返回圈子详情", manageDenied: "没有权限管理该圈子", circleInfo: "圈子信息", statusLabel: "状态：", postsLabel: "帖子：", commentsLabel: "评论：", createdLabel: "创建时间：", circleIntroduction: "圈子介绍", saving: "保存中...", saveCircle: "保存圈子信息", restoreCircle: "恢复圈子", deleteCircle: "删除圈子", noManagedPosts: "当前圈子还没有帖子。", authorLabel: "作者：", mediaLabel: "媒体：", reportsLabel: "举报：", restorePublic: "恢复公开", restorePost: "恢复帖子", postManageOwnersOnly: "仅作者或管理员可管理该帖子", circleComments: "圈子评论", noManagedComments: "当前圈子还没有评论。", restoreComment: "恢复评论", commentManageOwnersOnly: "仅作者或管理员可管理该评论", confirmDeleteCircle: "确认删除圈子", confirmDeletePost: "确认删除帖子", confirmDeleteComment: "确认删除评论", deleteCircleDescription: "删除后圈子会从公开列表、公开详情和发帖选择器中隐藏，但数据库记录仍保留。", deleteManagedPostDescription: "删除后该帖子会在公开页面隐藏。", deleteManagedCommentDescription: "删除后有回复的评论会显示删除占位。", target: "目标：{title}",
    newPostTitle: "新建帖子", newPostDescription: "登录后在 OpenGlass Hub 社区创建新帖子。", draftReady: "已带入设备讨论草稿", draftFrom: "当前草稿来自", productPage: "产品页。", draftEditable: "你可以自由修改标题和正文，只有点击提交后才会真正发帖。", createCircleDescription: "登录后在 OpenGlass Hub 创建圈子。", backNavigation: "返回导航", management: "管理", notificationsTitle: "通知", notificationsDescription: "查看你的互动通知。",
    loadingNotifications: "加载通知中...", loginNotifications: "请先登录后查看通知", notificationsFailed: "通知加载失败", unread: "未读 {count}", markAllRead: "全部已读", noNotifications: "暂无通知", systemInitial: "系",
    forbidden: "无权执行该操作。", operationFailed: "操作失败，请稍后重试。", loginDeletePost: "请先登录后再删除帖子。", deleteFailed: "删除失败。", hideFailed: "隐藏失败。", deletePost: "删除帖子", deletePostDetail: "删除后该帖子将从公开区移除，并跳回动态页。", irreversible: "该操作不可撤销。", confirmDelete: "确认删除", hidePost: "隐藏帖子", hidePostDetail: "隐藏后该帖子将从公开区移除，并跳回动态页。", hideConfirmQuestion: "确认执行隐藏操作？", confirmHide: "确认隐藏",
    commentsMigration: "评论互动数据库迁移尚未执行，请先运行 comments interactions migration。", commentsFailed: "加载评论失败", actionFailed: "操作失败", likeFailed: "点赞失败", loginFirst: "请先登录", author: "作者", pendingReview: "待审核", edited: "已编辑", commentDeleted: "该评论已删除", reply: "回复", delete: "删除", replyPlaceholder: "回复这条评论...", commentsArea: "评论区", loadingComments: "加载评论中...", noComments: "暂无评论，来发表第一条吧。", deleteComment: "删除评论", deleteCommentDetail: "删除后该评论将从公开区移除。若评论下已有回复，将显示为“该评论已删除”。",
    uploadRateLimited: "上传过于频繁，请稍后再试。", uploadVerification: "当前上传需要额外安全验证，请稍后再试。", coverUpdateFailed: "更新封面失败。", uploadGuardFailed: "上传校验失败", coverUnsupported: "当前环境未启用圈子图片字段，无法上传封面。", coverType: "圈子封面只支持 jpg / png / webp / gif。", coverSize: "圈子封面不能超过 5MB。", coverUploadFailed: "圈子封面上传失败。", coverUpdated: "圈子封面已更新。", coverClearUnsupported: "当前环境未启用圈子图片字段，无法清除封面。", coverCleared: "圈子封面已清除。", coverClearFailed: "清除封面失败。", clearCover: "清除封面", coverHint: "支持上传 jpg / png / webp / gif，单图不超过 5MB。", coverMigration: "当前环境未完成圈子图片 migration，先只能显示兼容封面。",
    circleTypes: { topic: "通用话题", device: "设备圈子", project: "项目圈子" }, circleTypeHints: { topic: "适合一般讨论、经验分享与问题交流", device: "围绕具体设备、眼镜或硬件展开讨论", project: "围绕项目、应用或持续协作展开讨论" },
    createRateLimited: "创建过于频繁，请稍后再试。", circleAuthExpired: "登录状态已失效，请重新登录后再创建圈子。", circleNameTaken: "圈子名称已存在，请换一个名称。", circleRejected: "该圈子内容可能违反社区规则，暂时无法创建。", circleSlugFailed: "圈子链接生成失败，请换一个名称后重试。", circleCreateForbidden: "当前账号暂时无法创建圈子，请检查数据库权限配置。", circleRlsMissing: "数据库还没有准备好 owner/RLS，请先执行最新 migration。", circleProfileMissing: "当前账号缺少 profile，请先重新登录或补齐资料。", circleCreateFailed: "圈子创建失败，请稍后重试。", circleType: "圈子类型", circleNameLength: "圈子名称需要在 2 - 40 个字符之间。", circleDescriptionLength: "圈子简介最多 200 个字符。", circleCreated: "圈子创建成功，正在跳转。", checkingLogin: "检查登录状态...", signInCreateCircle: "登录后可创建圈子", circleName: "圈子名称", circleOptionalDescription: "圈子简介（可选）", circleCoverLabel: "圈子封面", removeCover: "移除封面", coverPreview: "圈子封面预览", creating: "创建中...",
    recommended: "推荐", recommendedDescription: "按新鲜度、讨论度和收藏表现综合排序。",
    latest: "最新", latestDescription: "按发布时间倒序查看最新公开帖子。",
    hot: "热门", hotDescription: "聚焦近两周互动更高的公开帖子。",
    newPost: "发帖", page: "第 {page} 页", discuss: "讨论 {name}",
    discussHint: "这里不会自动发帖。你可以先浏览动态，也可以带着设备上下文去发一个新帖子。",
    startPost: "开始发帖", relatedPosts: "查相关帖子", browseCircles: "看看圈子", previous: "上一页", next: "下一页",
    recommendedCircles: "圈子推荐", all: "全部", circleDiscussion: "进入圈子查看当前公开讨论。",
    circles: "圈子", circlesDescription: "OpenGlass Hub 论坛圈子。按话题分类的 AR/AI 眼镜社区讨论。",
    circlesLead: "按品牌、设备与使用场景进入公开讨论，先看内容，再决定去哪里继续聊。",
    backFeed: "返回动态", createCircle: "创建圈子", circlesFailed: "加载圈子失败", noCircles: "暂时还没有公开圈子",
    created: "创建于 {date}", circleNotFound: "圈子未找到", circleNotFoundDetail: "该圈子可能不存在，或者当前还没有公开显示。",
    backCircles: "返回圈子列表", circleDescription: "{name} · OpenGlass Hub 论坛圈子", breadcrumb: "面包屑", home: "首页", forum: "论坛",
    circleCover: "{name} 圈子封面", reportCircle: "举报圈子", circlePosts: "圈子帖子", allFeed: "全部动态", postsFailed: "加载帖子失败",
    noCirclePosts: "该圈子还没有公开帖子", viewAllFeed: "查看全部动态", postNotFound: "帖子未找到",
    postNotFoundDetail: "该帖子可能已被删除、尚未公开，或者当前链接无效。", anonymous: "匿名", member: "社区成员",
    viewProfile: "查看 {name} 的资料", noBody: "此帖子没有正文内容。", comments: "评论", details: "查看详情",
    enterCircle: "进入圈子", circleFallback: "查看这个圈子的公开讨论与后续动态。", publicDiscussion: "公开讨论", circleInitial: "圈",
    postImage: "帖子图片", video: "视频", videoLink: "视频链接", openVideo: "打开视频链接",
    noPosts: "还没有公开帖子", noPostsDetail: "社区刚开始启动时，第一批讨论通常会围绕设备体验、选购求助、开发限制和 Gaze Launcher 建议展开。",
    firstPost: "写第一篇帖子", viewCircles: "查看圈子", deviceExperience: "设备体验", buyingHelp: "选购求助", developmentQuestions: "开发问题", launcherSuggestions: "Gaze Launcher 建议", channels: "论坛频道",
    types: { experience: "体验", question: "提问", review: "评测", dev: "开发", news: "资讯", feedback: "反馈" },
  },
  en: {
    tabFeed: "Feed", feed: "Post Feed", feedDescription: "Public OpenGlass Hub forum posts, sorted by recommended, latest or popular.",
    share: "Share", copied: "Copied", like: "Like", unlike: "Unlike", bookmark: "Bookmark", unbookmark: "Remove bookmark",
    composerTypes: { question: "Help", experience: "Text", review: "Experience / review", dev: "Development", news: "News", feedback: "Feedback" }, composerTypeHints: { question: "Compatibility, buying and usage questions.", experience: "General discussion, observations and additional details.", review: "Summaries, comparisons and long-term observations.", dev: "SDKs, permissions, input and system capabilities.", news: "Manually curated updates, announcements and observations.", feedback: "Suggestions for products, the community and Gaze Launcher." },
    imageMetadata: "Unable to read image metadata: {name}", videoMetadata: "Unable to read video metadata: {name}", actionRateLimited: "Too many actions. Please try again later.", postRejected: "This post may violate community rules and cannot be published.", invalidPostBody: "Body text must contain 1 to 50000 characters.", invalidCredentials: "Incorrect email or password.", emailUnconfirmed: "Please verify your email before logging in.", alreadyRegistered: "This email is already registered. Please log in.", videoUploadFailed: "Video upload failed.", videoInitFailed: "Video upload initialization failed", missingPublicAuthConfig: "Missing PUBLIC_SUPABASE_URL or PUBLIC_SUPABASE_ANON_KEY.", maxMedia: "A post can contain at most {count} media files.", mediaTypes: "Only jpg / png / webp / gif images and mp4 / webm / mov videos are supported.", imageMaxSize: "An image cannot exceed 50MB.", videoMaxSize: "A video cannot exceed 150MB.", oneVideo: "A post can contain at most 1 video.", totalMediaSize: "Total post media cannot exceed 150MB.", metadataFailed: "Unable to read media metadata.", createPostFailed: "Unable to create post", unknownError: "Unknown error", imageUploadFailed: "Image upload failed", mediaWriteFailed: "Unable to save media", videoReview: "Video submitted for review.", publishedRedirecting: "Published. Redirecting to the post...", postReview: "Post submitted for review.", published: "Published.", checkingAuth: "Checking login status...", loginPost: "Log in to continue posting", publishPost: "Publish post", deviceDraft: "A neutral draft from the {name} device page is ready to edit.", postType: "Post type", loadingCircles: "Loading circles...", noAvailableCircles: "No available circles", chooseCircle: "Choose a circle to post in", circleList: "Circle list", title: "Title", body: "Body", mediaFiles: "Media files", dropMedia: "Drop images or videos here, or choose files", cover: "Cover", image: "Image", currentCover: "Current cover", setCover: "Set as cover", submitPost: "Submit post",
    writeComment: "Share your thoughts...", commentPublished: "Comment published.", loginComment: "Please log in before commenting", requestFailed: "Request failed", commentReview: "Comment submitted for review.", submitFailed: "Submission failed", commentRejected: "This comment may violate community rules and cannot be published.", commentRateLimited: "Too many comments. Please try again later.", commentUnconfigured: "Comments are not configured", signInComment: "Log in to comment", goLogin: "Go to login", publishComment: "Write a comment", cancelReply: "Cancel reply", submitting: "Submitting...", publishReply: "Publish reply", submitComment: "Publish comment",
    checkingPermission: "Checking management permissions...", manageCircle: "Manage circle", confirm: "Confirm", cancel: "Cancel", processing: "Processing...", confirmationInput: "Enter confirmation",
    report: "Report", reportInvalid: "Invalid report. Please check and try again.", reportGone: "This content is no longer visible; no further report is needed.", reportRateLimited: "Too many submissions. Please try again later.", loginReport: "Please log in before reporting.", reportReasonShort: "Additional details must contain at least 5 characters.", reportFailed: "Report failed.", reportHandled: "This content is being handled or is no longer visible; no further report is needed.", reportDuplicate: "You recently reported this content. Administrators will handle it together.", reportSuccess: "Report submitted. Administrators will review it as soon as possible.", reportContent: "Report content", reportIntro: "Select a reason and add details for administrators to review.", reportDetails: "Additional details", reportDetailsPlaceholder: "Optional details to help administrators review", reportDetailsHint: "Optional; at least 5 characters if provided.", reportLoginHint: "Log in to submit a report. You will return to this page afterwards.", submitReport: "Submit report",
    reportReasons: { spam: "Spam", harassment: "Harassment or abuse", hate: "Hateful content", sexual: "Sexual content violations", violence: "Violence or threats", illegal: "Illegal content", off_platform_contact: "Off-platform solicitation", misinformation: "False or misleading information", privacy: "Privacy violation", other: "Other" },
    unsupportedVideo: "Your browser does not support this video.", expand: "Expand", openExternalVideo: "Open external video", externalVideoHint: "View external video in a new window.",
    mediaThumbnails: "Post media thumbnails", link: "Link", closeMedia: "Close media viewer", close: "Close", previousImage: "Previous image", nextImage: "Next image",
    unknownUser: "Unknown user", manageLoginRequired: "Log in to manage circles.", circleMissing: "Circle not found.", manageProfileMissing: "Your account has no profile and cannot manage circles.", manageForbidden: "You do not have permission to manage this circle.", contentManageForbidden: "You do not have permission to manage this content.", circleStatusMigration: "The circle status migration is not complete; the latest SQL is required.", circleDeleteRls: "Circle deletion permissions are not ready. Check circles RLS / policy.", circleDeleteFailed: "Unable to delete circle. Please try again later.", manageQueryFailed: "Unable to load circle management information. Please try again later.", manageLoadFailed: "Unable to load circle management data", circleUpdated: "Circle information updated.", circleUpdateFailed: "Unable to update circle", postStatusFailed: "Unable to update post status", postHidden: "Post hidden.", postRestored: "Post restored to public view.", postDeleted: "Post deleted.", circleDeleted: "Circle deleted.", circleRestored: "Circle restored.", circleStatusFailed: "Unable to update circle status", circleDeletedRedirect: "Circle deleted. Returning to circles...", commentRemoved: "Comment deleted.", commentRestored: "Comment restored.", commentStatusFailed: "Unable to update comment status", loadingManage: "Loading circle management data...", manageOwnedHint: "Log in to manage circles you created.", backCircleDetail: "Back to circle", manageDenied: "You cannot manage this circle", circleInfo: "Circle information", statusLabel: "Status: ", postsLabel: "Posts: ", commentsLabel: "Comments: ", createdLabel: "Created: ", circleIntroduction: "Circle description", saving: "Saving...", saveCircle: "Save circle information", restoreCircle: "Restore circle", deleteCircle: "Delete circle", noManagedPosts: "No posts in this circle yet.", authorLabel: "Author: ", mediaLabel: "Media: ", reportsLabel: "Reports: ", restorePublic: "Restore public view", restorePost: "Restore post", postManageOwnersOnly: "Only the author or administrators can manage this post", circleComments: "Circle comments", noManagedComments: "No comments in this circle yet.", restoreComment: "Restore comment", commentManageOwnersOnly: "Only the author or administrators can manage this comment", confirmDeleteCircle: "Confirm circle deletion", confirmDeletePost: "Confirm post deletion", confirmDeleteComment: "Confirm comment deletion", deleteCircleDescription: "The circle will be hidden from public lists, details and post selectors. Database records will remain.", deleteManagedPostDescription: "The post will be hidden from public pages.", deleteManagedCommentDescription: "Comments with replies will show a deleted-comment placeholder.", target: "Target: {title}",
    newPostTitle: "New post", newPostDescription: "Log in to create a new OpenGlass Hub community post.", draftReady: "Device discussion draft ready", draftFrom: "This draft comes from the", productPage: "product page.", draftEditable: "Edit the title and body freely. A post is created only when you submit.", createCircleDescription: "Log in to create an OpenGlass Hub circle.", backNavigation: "Back navigation", management: "Management", notificationsTitle: "Notifications", notificationsDescription: "View your interaction notifications.",
    loadingNotifications: "Loading notifications...", loginNotifications: "Please log in to view notifications", notificationsFailed: "Unable to load notifications", unread: "Unread {count}", markAllRead: "Mark all read", noNotifications: "No notifications", systemInitial: "S",
    forbidden: "You do not have permission for this action.", operationFailed: "Action failed. Please try again later.", loginDeletePost: "Please log in before deleting a post.", deleteFailed: "Deletion failed.", hideFailed: "Unable to hide content.", deletePost: "Delete post", deletePostDetail: "The post will be removed from public view and you will return to the feed.", irreversible: "This action cannot be undone.", confirmDelete: "Confirm deletion", hidePost: "Hide post", hidePostDetail: "The post will be hidden from public view and you will return to the feed.", hideConfirmQuestion: "Hide this post?", confirmHide: "Confirm hide",
    commentsMigration: "The comment interactions migration has not been applied.", commentsFailed: "Unable to load comments", actionFailed: "Action failed", likeFailed: "Unable to like", loginFirst: "Please log in", author: "Author", pendingReview: "Pending review", edited: "Edited", commentDeleted: "This comment has been deleted", reply: "Reply", delete: "Delete", replyPlaceholder: "Reply to this comment...", commentsArea: "Comments", loadingComments: "Loading comments...", noComments: "No comments yet. Be the first to comment.", deleteComment: "Delete comment", deleteCommentDetail: "The comment will be removed from public view. If it has replies, a deleted-comment placeholder will remain.",
    uploadRateLimited: "Too many uploads. Please try again later.", uploadVerification: "This upload requires additional security verification. Please try again later.", coverUpdateFailed: "Unable to update cover.", uploadGuardFailed: "Upload validation failed", coverUnsupported: "Circle image fields are not enabled; a cover cannot be uploaded.", coverType: "Circle covers support jpg / png / webp / gif only.", coverSize: "Circle covers cannot exceed 5MB.", coverUploadFailed: "Circle cover upload failed.", coverUpdated: "Circle cover updated.", coverClearUnsupported: "Circle image fields are not enabled; the cover cannot be cleared.", coverCleared: "Circle cover cleared.", coverClearFailed: "Unable to clear cover.", clearCover: "Clear cover", coverHint: "Upload jpg / png / webp / gif images up to 5MB.", coverMigration: "The circle image migration is not complete; only the compatible cover is available.",
    circleTypes: { topic: "General topic", device: "Device circle", project: "Project circle" }, circleTypeHints: { topic: "General discussions, experiences and questions", device: "Discussions about a specific device, glasses or hardware", project: "Projects, applications and ongoing collaboration" },
    createRateLimited: "Too many creations. Please try again later.", circleAuthExpired: "Your session expired. Log in again before creating a circle.", circleNameTaken: "Circle name already exists. Choose another name.", circleRejected: "This circle may violate community rules and cannot be created.", circleSlugFailed: "Unable to generate the circle link. Try another name.", circleCreateForbidden: "Your account cannot create a circle. Check the database permission configuration.", circleRlsMissing: "Database owner/RLS setup is not ready; the latest migration is required.", circleProfileMissing: "Your account has no profile. Log in again or complete your profile.", circleCreateFailed: "Unable to create circle. Please try again later.", circleType: "Circle type", circleNameLength: "Circle names must contain 2 - 40 characters.", circleDescriptionLength: "Circle descriptions cannot exceed 200 characters.", circleCreated: "Circle created. Redirecting...", checkingLogin: "Checking login status...", signInCreateCircle: "Log in to create a circle", circleName: "Circle name", circleOptionalDescription: "Circle description (optional)", circleCoverLabel: "Circle cover", removeCover: "Remove cover", coverPreview: "Circle cover preview", creating: "Creating...",
    recommended: "Recommended", recommendedDescription: "Ranked by freshness, discussion and bookmarks.",
    latest: "Latest", latestDescription: "Public posts in reverse publication order.",
    hot: "Popular", hotDescription: "Public posts with more activity in the past two weeks.",
    newPost: "New post", page: "Page {page}", discuss: "Discuss {name}",
    discussHint: "No post is created automatically. Browse the feed or start a new post with this device context.",
    startPost: "Start a post", relatedPosts: "Related posts", browseCircles: "Browse circles", previous: "Previous", next: "Next",
    recommendedCircles: "Suggested circles", all: "All", circleDiscussion: "Enter this circle to view public discussions.",
    circles: "Circles", circlesDescription: "OpenGlass Hub forum circles: AR/AI glasses discussions organized by topic.",
    circlesLead: "Explore public discussions by brand, device and use case before joining the conversation.",
    backFeed: "Back to feed", createCircle: "Create circle", circlesFailed: "Unable to load circles", noCircles: "No public circles yet",
    created: "Created {date}", circleNotFound: "Circle not found", circleNotFoundDetail: "This circle may not exist or may not be public yet.",
    backCircles: "Back to circles", circleDescription: "{name} · OpenGlass Hub forum circle", breadcrumb: "Breadcrumb", home: "Home", forum: "Forum",
    circleCover: "{name} circle cover", reportCircle: "Report circle", circlePosts: "Circle posts", allFeed: "All posts", postsFailed: "Unable to load posts",
    noCirclePosts: "No public posts in this circle yet", viewAllFeed: "View all posts", postNotFound: "Post not found",
    postNotFoundDetail: "This post may have been deleted, may not be public or may have an invalid link.", anonymous: "Anonymous", member: "Community member",
    viewProfile: "View {name}'s profile", noBody: "This post has no body text.", comments: "Comments", details: "View details",
    enterCircle: "Enter circle", circleFallback: "View this circle's public discussions and updates.", publicDiscussion: "Public discussion", circleInitial: "C",
    postImage: "Post image", video: "Video", videoLink: "Video link", openVideo: "Open video link",
    noPosts: "No public posts yet", noPostsDetail: "Early discussions may cover device experiences, buying advice, development constraints and Gaze Launcher suggestions.",
    firstPost: "Write the first post", viewCircles: "View circles", deviceExperience: "Device experiences", buyingHelp: "Buying advice", developmentQuestions: "Development questions", launcherSuggestions: "Gaze Launcher suggestions", channels: "Forum channels",
    types: { experience: "Experience", question: "Question", review: "Review", dev: "Development", news: "News", feedback: "Feedback" },
  },
} as const;

export function localizeCommunityStatus(message: string | undefined, locale: ResolvedLocale): string | undefined {
  const text = communityMessages[locale];
  // Only application-owned status copy is translated; unknown provider/user text is retained.
  switch (message) {
    case "Comment published.": return text.commentPublished;
    case "Comment submitted for review.": return text.commentReview;
    case "Post published.": return text.published;
    case "Post submitted for review.": return text.postReview;
    default: return message;
  }
}

export function formatCommunityPostTime(createdAt: string | Date, locale: ResolvedLocale, now = new Date()): string {
  if (locale === "zh-CN") return formatPostTime(createdAt, now);
  const created = createdAt instanceof Date ? createdAt : new Date(createdAt);
  if (Number.isNaN(created.getTime())) return typeof createdAt === "string" ? createdAt : "";
  const minutes = Math.floor(Math.max(0, now.getTime() - created.getTime()) / 60000);
  if (minutes < 1) return "Just posted";
  if (minutes < 10) return `Posted ${minutes} ${minutes === 1 ? "minute" : "minutes"} ago`;
  return new Intl.DateTimeFormat(locale, { year: "numeric", month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(created);
}
